### ISSUE TITLE
How can I set max-size for all the chunk files and entry file main.js by 205kb

### ISSUE THREAD

**Issue by rathorebs** [ModusCreateOrg/budgeting#117]
## Description
01) How can I set max-size for all the chunk files.
02) How can I reduce or split main.js file.

## Steps to reproduce

01) npm run build > after build my chunk files and main.js will get bigger(more then 300kb).

## Expected Behavior

01) I don't want to my chunk file size more then 250kb
02) I don't want to my entry point file(main.js) size more then 250kb

## Additional Details

Please see attached file.
![issue](https://user-images.githubusercontent.com/9293248/32132138-99cf5d22-bbdb-11e7-872a-e27ca6e908a9.jpg)

**Comment by grgur** [comment]
@rathorebs code has been updated with webpack 4 and chunks are now significantly optimized. Please have a look
