### ISSUE TITLE
Are your working to upgrade this repository.

### ISSUE THREAD

**Issue by rathorebs** [ModusCreateOrg/budgeting#178]
## Description
Hi Team,

I'm waiting for your updated "Budgeting App" with Webpack v4, ES8 or ES7, React v16, and Redux v4.

Thanks,
BSR

**Comment by grgur** [comment]
@rathorebs actually yes, it's in the works. Webpack v4 has been upgraded and we're working on a few extra tweaks (e.g. async loading of heavy libs). Shouldn't be too long before we push that

**Comment by rathorebs** [comment]
Thanks :+1:

**Comment by rathorebs** [comment]
When will you push Webpack v4 upgraded repo.

**Comment by grgur** [comment]
I'll try to push something next week. Thanks for remaining patient :)

**Comment by grgur** [comment]
Here's the WIP branch https://github.com/ModusCreateOrg/budgeting/pull/180

**Comment by grgur** [comment]
#180 merged. We now support Webpack 4.x, React 16.4.x and so on.
