### ISSUE TITLE
switch to redux saga as middleware to handle async actions

### ISSUE THREAD

**Issue by nelsonomuto** [ModusCreateOrg/budgeting#184]
## Description
Use redux sagas instead of thunk 

## Steps to reproduce
N/A

## Observed Behavior
not using sagas

## Expected Behavior
use sagas to make async actions more predictable and easier to test

## Additional Details
https://decembersoft.com/posts/redux-thunk-vs-redux-saga/

**Comment by grgur** [comment]
Thanks, good idea. We decided to stick with thunk because it's easier to understand.
