### ISSUE TITLE
Automatically format files using Prettier in a pre-commit hook

### ISSUE THREAD

**Issue by ecris87** [ModusCreateOrg/budgeting#188]
Automatically format files using Prettier in a pre-commit hook. Guide: https://prettier.io/docs/en/precommit.html

Going with option 1, this would require adding 2 new dev dependencies: lint-staged and husky.

**Comment by grgur** [comment]
Let's set up `husky` and `lint-staged` for that

**Comment by nelsonomuto** [comment]
@grgur any more issues you see with the PR or is it good?

**Comment by grgur** [comment]
@nelsonomuto there's an issue that I reported in #188. Please take a look there

**Comment by ecris87** [comment]
@nelsonomuto Thank you!
