### ISSUE TITLE
[Request] PWA support

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/budgeting#189]
Let's make this a PWA

**Comment by grgur** [comment]
#190 works like a charm, but we may also need offline support.

Also, I recommend testing in private mode where Chrome plugins are not obstructing performance

![image](https://user-images.githubusercontent.com/733074/44996531-b1f83380-afa8-11e8-8d7a-c2ca29ac856b.png)

**Comment by ecris87** [comment]
@grgur thanks, will check in private mode from now on. I'll continue with offline support 👍

**Comment by ecris87** [comment]
Now this looks good on production:

![image](https://user-images.githubusercontent.com/5598081/45142374-0aa21900-b1c1-11e8-8d95-0df999fb6378.png)
