### ISSUE TITLE
404 when accessing /budget directly

### ISSUE THREAD

**Issue by ecris87** [ModusCreateOrg/budgeting#196]
## Steps to reproduce
- Visit https://budget.modus.app/budget or any other route directly

## Observed Behavior
- This results in a 404 Page not found error.

## Expected Behavior
- Content corresponding to the given route is displayed.

## Screenshots
![image](https://user-images.githubusercontent.com/5598081/45032287-250db280-b05a-11e8-9af8-a7d7ae0eaa61.png)

__Potential solution:__
- Now that the app has switched from HashRouter to BrowserRouter the server could be configured to redirect 404s to /, essentially letting the client handle them.

**Comment by grgur** [comment]
Can you try unregistering the service worker and clearing cache? This should have been fixed in #197

**Comment by ecris87** [comment]
Confirming it works now. The routes no longer return 404s when accessed directly.

There is an issue with the service worker though. Checking PWA:  

![image](https://user-images.githubusercontent.com/5598081/45090435-00781000-b118-11e8-91ac-a064acf916be.png)

Is it something that can be solved using the redirects file?
